# Adapted from https://raw.githubusercontent.com/RudyMis/Bubbles/master/.github/workflows/godot-ci.yml

name: godot-ci

on:
  push:
    branches: [ master ]

env:
  EXPORT_NAME: LD57
  GODOT_VERSION: 4.4.1

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          apt-get update && apt-get install -y rsync

      - name: Web Build
        run: |
          mkdir ./$EXPORT_NAME
          rsync -Rr . ./$EXPORT_NAME
          cd $EXPORT_NAME
          mkdir -v -p build/web
          godot -v --headless --export-release "Web" build/web/index.html

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ${{ env.EXPORT_NAME }}/build/web

      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ld57
          ITCH_USER: d0v1d
          PACKAGE: ${{ env.EXPORT_NAME }}/build/web

      - name: Notify Discord Channel
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '<@245327587369287682> <@245327587369287682> <@245327587369287682> IL AVAIT LES MOTS !!! ??? https://d0v1d.itch.io/ld57 <@245327587369287682> <@245327587369287682> <@245327587369287682> !'
